<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    <script>
      /* let err = new Error("出错了");
      console.dir(err);
      console.log(err.message); // 出错了
      console.log(err.name); // Error
      console.log(err.stack); // ...
      let i = 0;
      i += 1;
      console.log(i); */
    </script>
    <script>
      /* function throwIt() {
        throw new Error("");
      }

      function catchIt() {
        try {
          throwIt();
        } catch (e) {
          console.log(e.stack); // print stack trace
        }
      }

      catchIt(); */
    </script>
    <script>
      /* let b = a;
      console.log(b); //Uncaught ReferenceError: a is not defined */

      /* let b+2=1;
      console.log(b);
      // Uncaught SyntaxError: Unexpected token + */

      /* function fn(){
        return 12;
      }
      fn()=13;
      // Uncaught ReferenceError: Invalid left-hand side in assignment */

      /* function fn(){
        this=12;
        return 12;
      }
      fn();
      // Uncaught ReferenceError: Invalid left-hand side in assignment */

      /* let arr = [1, 2];
      arr.length = -1;
      // Uncaught RangeError: Invalid array length */

      /* let b = new true();
      // Uncaught TypeError: true is not a constructor */

      /* let n = new "str"();
      // Uncaught TypeError: "str" is not a constructor */

      /* let n = new 123();
      // Uncaught TypeError: 123 is not a constructor */

      /* null.toString();
      // Uncaught TypeError: Cannot read property 'toString' of null */

      /* undefined.toString();
      // Uncaught TypeError: Cannot read property 'toString' of undefined */

      /* let obj = {};
      console.log(obj.start); // undefined
      obj.start(); 
      //Uncaught TypeError: obj.start is not a function */

      // encodeURI('\uD800');
      // Uncaught URIError: URI malformed

      // encodeURIComponent('\uD800');
      // Uncaught URIError: URI malformed

      /* var err1 = new Error("出错了！");
      var err2 = new RangeError("出错了，变量超出有效范围！");
      var err3 = new TypeError("出错了，变量类型无效！");

      console.log(err1.message); // "出错了！"
      console.log(err2.message); // "出错了，变量超出有效范围！"
      console.log(err3.message); // "出错了，变量类型无效！" */

      /* function UserError(message) {
        this.message = message || "默认信息";
        this.name = "UserError";
      }

      UserError.prototype = new Error();
      UserError.prototype.constructor = UserError;

      let typeE = new UserError("类型错误");
      console.log(typeE.name, typeE.message); */

      /* if (x < 0) {
        throw new Error("x 必须为正数");
      }
      // Uncaught ReferenceError: x is not defined
      console.log("23"); */

      // throw new Error("哈哈哈哈哈");
      // Uncaught Error: 哈哈哈哈哈

      // throw new Error(null);
      // Uncaught Error: null

      // throw new Error(undefined);
      // Uncaught Error

      // throw new Error(123);
      // Uncaught Error: 123

      // throw new Error({});
      // Uncaught Error: [object Object]

      /* try {
        throw new Error("出错了!");
      } catch (e) {
        console.error(e.name + ": " + e.message);
      } */

      /* function cleansUp() {
        try {
          throw new Error("出错了……");
          console.log("此行不会执行");
        } finally {
          console.log("完成清理工作");
        }
      }

      cleansUp(); */

      /* function idle(x) {
        try {
          console.log(x);
          return "result";
        } finally {
          console.log("FINALLY");
        }
      }

      console.log(idle("hello")); */

      /* var count = 0;
      function countUp() {
        try {
          // return count;
          throw count;
        } catch {
          console.log(count); //0
          return "catch";
        } finally {
          count++;
          console.log(count);
        }
      }

      console.log(countUp()); */
      // 0

      /* function f() {
        try {
          console.log(0);
          throw "bug";
        } catch (e) {
          console.log(1);
          return true; // 这句原本会延迟到 finally 代码块结束再执行
          console.log(2); // 不会运行
        } finally {
          console.log(3);
          return false; // 这句会覆盖掉前面那句 return
          console.log(4); // 不会运行
        }

        console.log(5); // 不会运行
      }

      var result = f();

      console.log(result); */

      /* function f() {
        try {
          throw "出错了！";
        } catch (e) {
          console.log("捕捉到内部错误");
          throw e; // 这句原本会等到finally结束再执行
        } finally {
          // return false; // 直接返回
        }
      }

      try {
        f();
      } catch (e) {
        // 此处不会执行
        console.log('caught outer "bogus"');
      }

      // 捕捉到内部错误 */

      /* Promise.resolve(1)
        .then(res => {
          console.log(res); // 1
          // throw new Error("something went wrong");
          return Promise.resolve(2);
        })
        .then(res => {
          console.log(res); // 2
        })
        .catch(err => {
          // not catch err
          console.error(err);
          return Promise.resolve(3);
        })
        .then(res => {
          // not exe Promise.resolve()
          // params is undefined
          console.log(res); // undefined
        })
        .catch(err => {
          // not catch err
          console.error(err);
        }); */

      /* function someFuncThatThrowsAnError() {
        localStorage.setItem("aa", "aaa");
        return localStorage.getItem("aa");
      }

      (async function() {
        try {
          await someFuncThatThrowsAnError();
        } catch (err) {
          console.error(err);
        }

        console.log("Easy!");
      })();

      // Easy! */

      /* function someFuncThatThrowsAnError() {
        throw new Error("123");
      }

      (async function() {
        try {
          await someFuncThatThrowsAnError();
        } catch (err) {
          console.error(err);
        }

        console.log("Easy!");
      })();

      // Error: 123 at someFuncThatThrowsAnError
      // Easy! */

      /* function c() {
        try {
          var bar = baz;
          throw new Error();
        } catch (e) {
          console.log(e.stack);
        }
      }

      function b() {
        c();
      }

      function a() {
        b();
      }
      a();
      // ReferenceError: baz is not defined
      //   at c(file:///...)
      //   at b(file:///...)
      //   at a(file:///...)
      //   at file:///C:/ */

      /* function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject("我可以被捕获");
            // throw Error('永远无法被捕获')
          });
        });
      }

      Promise.resolve(true)
        .then((resolve, reject) => {
          return thirdFunction();
        })
        .catch(error => {
          console.error("捕获异常", error); // 捕获异常 我可以被捕获
        }); */

      /* function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            // reject("我可以被捕获");
            throw Error("永远无法被捕获"); 
            //Uncaught Error: 永远无法被捕获
          });
        });
      }

      Promise.resolve(true)
        .then((resolve, reject) => {
          return thirdFunction();
        })
        .catch(error => {
          console.error("捕获异常", error); //
        }); */

      /* function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject(new Error("我可以被捕获"));
            // throw Error("永远无法被捕获"); 
          });
        });
      }

      Promise.resolve(true)
        .then((resolve, reject) => {
          return thirdFunction();
        })
        .catch(error => {
          console.error("捕获异常", error); //捕获异常 Error: 我可以被捕获
        }); */

      /* function fetch(callback) {
        setTimeout(() => {
          console.log("请求失败");//请求失败
        });
      }

      fetch(() => {
        console.log("请求处理"); // 永远不会执行
      }); */

      /* function fetch(callback) {
        callback();
        setTimeout(() => {
          console.log("请求失败"); // 请求失败
        });
      }

      fetch(() => {
        console.log("请求处理"); // 请求处理
      }); */

      /* function fetch(callback) {
        setTimeout(() => {
          throw Error("请求失败");
          // Uncaught Error: 请求失败 at setTimeout
        });
      }

      try {
        fetch(() => {
          console.log("请求处理"); // 永远不会执行
        });
      } catch (error) {
        console.log("触发异常", error); // 永远不会执行
      } */

      /* function fetch(handleError, callback) {
        setTimeout(() => {
          handleError("请求失败");
        });
      }

      fetch(
        () => {
          console.log("失败处理"); // 失败处理
        },
        error => {
          console.log("请求处理"); // 永远不会执行
        }
      ); */

      /* new Promise((resolve, reject) => {
        resolve("ok");
      }).then(result => {
        console.log(result); // ok
      }); */

      /* new Promise((resolve, reject) => {
        reject("no");
      }).then(
        result => {
          console.log(result); // 永远不会执行
        },
        error => {
          console.log(error); // no
        }
      ); */

      /* new Promise((resolve, reject) => {
        console.log("nothing"); // nothing
        // nothing
      }).then(
        result => {
          console.log(result); // 永远不会执行
        },
        error => {
          console.log(error); // 永远不会执行
        }
      ); */

      /* new Promise((resolve, reject) => {
        reject("no");
      })
        .then(
          result => {
            console.log(result); // 永远不会执行
          },
          error => {
            console.log(error);
          }
        )
        .catch(error => {
          console.log(error); // no
        }); */

      /* console.log(
        new Promise((resolve, reject) => {
          resolve("ok");
          // reject("no");
        })
      ); */

      /* new Promise((resolve, reject) => {
        return resolve(
          new Promise((resolve, reject) => {
            resolve("ok");
          })
        );
      }).then(
        result => {
          console.log(result);
        },
        error => {
          console.log(error);
        }
      ); */

      /* console.log(new Promise((resolve, reject) => {
          return new Promise((resolve, reject) => {
            resolve("ok");
          });
        }))*/

      /* new Promise((resolve, reject) => {
        resolve("ok");
      })
        .then(result => {
          return Promise.reject("error1");
        })
        .then(result => {
          console.log(result); // 永远不会执行
          return Promise.resolve("ok1"); // 永远不会执行
        })
        .then(result => {
          console.log(result); // 永远不会执行
        })
        .catch(error => {
          console.log(error); // error1
        }); */

      /* function fetch(callback) {
        return new Promise((resolve, reject) => {
          throw Error("用户不存在");
        });
      }

      fetch()
        .then(result => {
          console.log("请求处理", result); // 永远不会执行
        })
        .catch(error => {
          console.log("请求处理异常", error); // 请求处理异常 用户不存在
        });

      // 请求处理异常 Error: 用户不存在
      //   at Promise
      //   at new Promise
      //   at fetch
      //   at file */

      /* function fetch(callback) {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            throw Error("用户不存在");
          });
        });
      }

      fetch()
        .then(result => {
          console.log("请求处理", result); // 永远不会执行
        })
        .catch(error => {
          console.log("请求处理异常", error); // 永远不会执行
        });

      // 程序崩溃
      // Uncaught Error: 用户不存在 */

      /* Promise.resolve(true)
        .then((resolve) => {
          throw Error("microTask 中的异常");
        })
        .catch(error => {
          console.log("捕获异常", error);
          // 捕获异常 Error: microTask 中的异常
          //   at Promise.resolve.then
        });
      Promise.reject(true)
        .then((resolve) => {
          throw Error("microTask 中的异常");
        })
        .catch(error => {
          console.log("捕获异常", error);
          // 捕获异常 true
        }); */

      /* Promise.resolve(true)
        .then(
          resolve => {
            throw Error("resolve 中的异常");
          },
          reject => {
            throw Error("reject 中的异常");
          }
        )
        .catch(error => {
          console.log("捕获异常", error);
          // 捕获异常 Error: resolve 中的异常
          //   at Promise.resolve.then.resolve
        });

      Promise.reject(true)
        .then(
          resolve => {
            throw Error("resolve 中的异常");
          },
          reject => {
            throw Error("reject 中的异常");
          }
        )
        .catch(error => {
          console.log("捕获异常", error);
          // 捕获异常 Error: reject 中的异常
          //   at Promise.reject.then.reject
        }); */

      /* function thirdFunction() {
        setTimeout(() => {
          throw Error("就是任性");
        });
      }

      Promise.resolve(true)
        .then(
          resolve => {
            console.log("resolve--1");
            thirdFunction();
          },
          reject => {
            console.log("reject--1");
            thirdFunction();
          }
        )
        .catch(error => {
          console.log("捕获异常", error);
        });

      Promise.reject(true)
        .then(
          resolve => {
            console.log("resolve--2");
            thirdFunction();
          },
          reject => {
            console.log("reject--2");
            thirdFunction();
          }
        )
        .catch(error => {
          console.log("捕获异常", error);
        }); */

      /* function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject("收敛一些");
          });
        });
      }

      Promise.resolve(true)
        .then(resolve => {
          thirdFunction();
        })
        .catch(error => {
          console.log("捕获异常", error); // 捕获异常 收敛一些
        });

      Promise.reject(true)
        .then(
          resolve => {
            thirdFunction();
          },
          reject => {
            return thirdFunction();
          }
        )
        .catch(error => {
          console.log("捕获异常", error); // 捕获异常 收敛一些
        }); */

      function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject("收敛一些");
          });
        });
      }

      /* Promise.resolve(true)
        .then(resolve => {
          console.log("1"); // 1
          return thirdFunction()
            .then(() => {
              console.log("2");
              return thirdFunction();
            })
            .then(() => {
              console.log("3");
              return thirdFunction();
            })
            .then(() => {
              console.log("4");
            });
        })
        .catch(error => {
          console.log("捕获异常", error);
          // 捕获异常 收敛一些
        }); */

      function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject("收敛一些");
          });
        });
      }
      Promise.resolve(true)
        .then(resolve => {
          console.log("1"); // 1
          return thirdFunction()
            .then(
              () => {
                console.log("2");
                return thirdFunction();
              },
              () => {
                console.log("2-");
                return thirdFunction();
              }
            )
            .then(
              () => {
                console.log("3");
                return thirdFunction();
              },
              () => {
                console.log("3-");
                return thirdFunction();
              }
            )
            .then(
              () => {
                console.log("4");
                return thirdFunction();
              },
              () => {
                console.log("4-");
                return thirdFunction();
              }
            );
        })
        .catch(error => {
          console.log("捕获异常", error);
        });
        // 1
        // 2-
        // 3-
        // 4-

      /* function thirdFunction() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            reject("收敛一些");
          });
        });
      }
      Promise.reject(true)
        .then(
          resolve => {},
          reject => {
            console.log("1"); // 1
            return thirdFunction()
              .then(
                () => {
                  console.log("2");
                  return thirdFunction();
                },
                () => {
                  console.log("2-");
                  return thirdFunction();
                }
              )
              .then(
                () => {
                  console.log("3");
                  return thirdFunction();
                },
                () => {
                  console.log("3-");
                  return thirdFunction();
                }
              )
              .then(
                () => {
                  console.log("4");
                  return thirdFunction();
                },
                () => {
                  console.log("4-");
                  return thirdFunction();
                }
              );
          }
        )
        .catch(error => {
          console.log("捕获异常", error);
        });
      // 1
      // 2-
      // 3-
      // 4-
      // 捕获异常 收敛一些 */
    </script>
  </body>
</html>
